from django.contrib.auth import validators
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
=======
    dependencies = [
        ("auth", "0007_alter_validators_add_error_messages"),
>>>>>>> 32e7214c1350fb4a88064960159c92207483e581
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'A user with that username already exists.'},
                help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                max_length=150,
                unique=True,
                validators=[validators.UnicodeUsernameValidator()],
                verbose_name='username',
=======
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text=(
                    "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ "
                    "only."
                ),
                max_length=150,
                unique=True,
                validators=[validators.UnicodeUsernameValidator()],
                verbose_name="username",
>>>>>>> 32e7214c1350fb4a88064960159c92207483e581
            ),
        ),
    ]
